# Generated by Django 4.2.16 on 2024-09-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_likepost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likepost",
            old_name="psot_id",
            new_name="post_id",
        ),
    ]
